// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbUPznQbk3ZWQOvqVecx4Yb3O_XUcIz2I',
    appId: '1:387474758695:web:8ddbb93fd94160ed7e4202',
    messagingSenderId: '387474758695',
    projectId: 'zoom-clone-fcb58',
    authDomain: 'zoom-clone-fcb58.firebaseapp.com',
    storageBucket: 'zoom-clone-fcb58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL8q_bakxQT3xrG5JRkUwhYRpnNjIc_v0',
    appId: '1:387474758695:android:8964962601a50dbe7e4202',
    messagingSenderId: '387474758695',
    projectId: 'zoom-clone-fcb58',
    storageBucket: 'zoom-clone-fcb58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSBYWo3dB5w0YW6I4b1hDlRo-BfQvbBjw',
    appId: '1:387474758695:ios:58d0f72edb828aff7e4202',
    messagingSenderId: '387474758695',
    projectId: 'zoom-clone-fcb58',
    storageBucket: 'zoom-clone-fcb58.appspot.com',
    androidClientId: '387474758695-vltrtlmboaaep0lje0g0o88fqs4v9mss.apps.googleusercontent.com',
    iosClientId: '387474758695-ul7o3r96ntsthdc17arn2tefjefi3jvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSBYWo3dB5w0YW6I4b1hDlRo-BfQvbBjw',
    appId: '1:387474758695:ios:8a8e318e8e5955d57e4202',
    messagingSenderId: '387474758695',
    projectId: 'zoom-clone-fcb58',
    storageBucket: 'zoom-clone-fcb58.appspot.com',
    androidClientId: '387474758695-vltrtlmboaaep0lje0g0o88fqs4v9mss.apps.googleusercontent.com',
    iosClientId: '387474758695-59851aqueb7hnq3fga6nc2a29v2jdojp.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone.RunnerTests',
  );
}
